//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova_Q2_Laercio_POO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_Info
    {
        public int cli_Id_Cliente { get; set; }
        public string cli_NomeCliente { get; set; }
        public decimal cli_Celular { get; set; }
        public string cli_Cidade { get; set; }
        public string cli_Estado { get; set; }
    }
}
